## Strings (`str`)
Strings are immutable sequences of characters. They support indexing and slicing.

In [93]:
# Note that I intentionally did not include any comments. You should add comments to explain the code.
# Your assignment includes adding comments to all code cells.
text = "Engineering"
print("First character:", text[0]) # Each character is indexed, starting from 0.
print("Slice:", text[1:5])

# Your code here to print out diffent characters and slices of the string.

First character: E
Slice: ngin


In [94]:
text = "Popcorn"
print("Middle Character:", text[3]) #Will print out the 4th character in the string since the count starts from 0
print("Slice:", text[0:3]) #this will cause the characters to be printed from the index 

Middle Character: c
Slice: Pop


## Lists (`list`) [ ]
Lists are ordered and mutable collections. They can contain mixed types and be nested.

In [95]:
data = [ 1, "temp",[2.7,8] ,"Microwave", [3.5, 4.2]] # You should change the nested array to 5 elements.
print("Second element:", data[1])
print("Nested list:", data[2]) # Do you need to change anything on this line? Why or why not?
print("Second element in the nested list:", data[2][1]) # What do you expect to see?
print("Last element:", data[4])

Second element: temp
Nested list: [2.7, 8]
Second element in the nested list: 8
Last element: [3.5, 4.2]


## Tuples (`tuple`) ( )
Tuples are ordered and immutable collections.

In [96]:
point = (3, 4, 5)
print("X coordinate:", point[0])
print("Y coordinate:", point[1])
print("Z coordinate:", point[2])
# Your code here to print out different elements of the tuple.i.e, the Y or Z element.

X coordinate: 3
Y coordinate: 4
Z coordinate: 5


In [97]:
point = (7.5, 8, 12)
print("X coordinate:", point[0],",",  "Y coordinate:", point[1],",",  "Z coordinate:", point[2]) 
#Code can be printed in the two ways above

X coordinate: 7.5 , Y coordinate: 8 , Z coordinate: 12


## Sets (`set`) { }
Sets are unordered collections of unique elements.

In [98]:
sensors = {"temp", "pressure", "temp", "length", "weight", "time", "light"} # Add more elements to the set.
print("Set contents:", sensors)
print("Is 'temp' in sensors?", "temp" in sensors)
# Note that sets are unordered. You cannot access elements by index.
# Your code here to add more elements and check membership of other elements.

Set contents: {'length', 'light', 'time', 'temp', 'pressure', 'weight'}
Is 'temp' in sensors? True


## Dictionaries (`dict`) { "key1":, "key2": .....}
Dictionaries store key-value pairs and allow fast lookup using keys.

In [99]:
sensor_data = {"temp": 22.5, "pressure": 101.3, "weight": 38.8, "time": 35.8} # Add more key-value pairs to the dictionary.
print("Temperature:", sensor_data["temp"], ",", "Weight:", sensor_data["weight"])
# Your code here to print out different values using their keys and add new key-value pairs.

Temperature: 22.5 , Weight: 38.8


### Example- 🛒 Grocery Bill Calculator

Loop through a list of grocery items and their prices shown in the code. Calculate the total bill. Apply a 5% discount if the total exceeds $50. Print out the total bill and an indication on whether a discount is applied. 

Hint: You will need a for loop through this list and then a conditional statement to determine if a discount can be applied. 

In [100]:
items = {'Milk': 4.5, 'Bread': 3.2, 'Eggs': 6.0, 'Cheese': 8.5, 'Fruits': 12.0, 'Vegetables': 10.0, 'Snacks': 9.0, 'Beverages': 7.5}
# You can add/delete items if you want
total = 0.0
total_item = 0

# Iterate through items and sum prices
for name, price in items.items():
    total += price
    total_item += 1
    print(f"{name} costs ${price:.2f}")
if total > 50:
    discount = total * 0.05 #5% discount added for the total bill if it exceeds $50
    total -= discount
    print(f"Discount applied: ${discount:.2f}")
    
print(f"Total grocery bill is ${total:.2f} for {total_item} items.")


Milk costs $4.50
Bread costs $3.20
Eggs costs $6.00
Cheese costs $8.50
Fruits costs $12.00
Vegetables costs $10.00
Snacks costs $9.00
Beverages costs $7.50
Discount applied: $3.04
Total grocery bill is $57.67 for 8 items.


## NumPy Arrays (`np.array( )`)
NumPy arrays are efficient for numerical data and support vectorized operations. Here is a simple example. We will dicsuss how to use NumPy Arrays more in future lectures. 

In [101]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5], 
                 [7, 8]])
print("Second element of arr1 multiplied by 2:", arr1[1]*2)
print("Array 2:")
print(arr2)

Second element of arr1 multiplied by 2: 4
Array 2:
[[4 5]
 [7 8]]


In [102]:
# Your code here to print out a 5 x 3 numpy array and the entire array multiplied by 2.

import numpy as np
arr1 = np.array([[5, 6, 7, 1, 3],
                 [3, 7, 1, 2, 7],
                 [1, 2, 3, 4, 5]])
print("Entire array multiplied by 2:")
print(arr1 * 2)

Entire array multiplied by 2:
[[10 12 14  2  6]
 [ 6 14  2  4 14]
 [ 2  4  6  8 10]]


## Sorting
Python lists can be sorted using the built-in `sorted()` function or the `.sort()` method.

In [103]:
numbers = [5, 2, 9, 1, 5, 6]
print("Original:", numbers)

numbers.sort()
sorted_numbers = sorted(numbers) # uncomment this line if you want to use sorted() instead of sort()

print("Sorted:  ", numbers)
print("Sorted:  ", sorted_numbers) # when you uncomment sorted_numbers

Original: [5, 2, 9, 1, 5, 6]
Sorted:   [1, 2, 5, 5, 6, 9]
Sorted:   [1, 2, 5, 5, 6, 9]


In [104]:
# Your code here
# Make up a list (any type you want) and sort them. Print out the original and sorted lists.
# You can only use sorted() function
words = ["pancakes", "bacon", "eggs", "waffles", "orange juice"] 
print("Original list:", words)
print("Sorted list:", sorted(words))

Original list: ['pancakes', 'bacon', 'eggs', 'waffles', 'orange juice']
Sorted list: ['bacon', 'eggs', 'orange juice', 'pancakes', 'waffles']


In [105]:
# Your code here
# Make up a list (any type you want) and sort them. Print out the original and sorted lists.
# You can only use .sort() method.
letter = ["s", "a", "p", "l", "g", "k", "w"]
print("OG List:", letter)
letter.sort()
print("Sorted:", letter)

OG List: ['s', 'a', 'p', 'l', 'g', 'k', 'w']
Sorted: ['a', 'g', 'k', 'l', 'p', 's', 'w']


### Sort a list of tuples usign a *lambda* function
A `lambda` function in Python is an anonymous, single-expression function. It is defined using the `lambda` keyword and allows for the creation of small, inline functions without needing to use the def keyword or assign a name. `lambda` functions are particularly useful in situations where a small, one-off function is needed as an argument to a higher-order function (a function that takes other functions as arguments). We will discuss more in future lectures. 

In [106]:
my_list = [(1, 'apple'), (2, 'orange'), (3, 'banana')] # List of tuples
my_list.sort(key= lambda item: item[1]) # Sorts by the first element of each tuple
print("Sorted by first element:", my_list)
# You should change the list an print out the sorted list based on different elements.


Sorted by first element: [(1, 'apple'), (3, 'banana'), (2, 'orange')]


In [107]:
# Your code here.  
# Make up a list of tuples (anything you want) and sort them. 
# Print out the original and sorted lists.
list = [(2, 'dog'), (1, 'fish'), (3, 'giraffe'), (4, 'cat'), (5, 'rooster')]
list.sort(key= lambda item: item[1])
print("My List:", list)

My List: [(4, 'cat'), (2, 'dog'), (1, 'fish'), (3, 'giraffe'), (5, 'rooster')]


### Sorting Dictionaries by Values
Need to use `sorted()` with a `lambda` function to sort *dictionary* items by value. Cannot use `.sort`

In [108]:
grades = {'Alice': 88, 'Bob': 95, 'Charlie': 78} # dictionary items
sorted_grades = sorted(grades.items(), key=lambda x: x[1])
print("Sorted by value:", sorted_grades)

Sorted by value: [('Charlie', 78), ('Alice', 88), ('Bob', 95)]


In [109]:
# Your code here
# Make up an array of dictionary items (any type you want) and sort them.
# Print out the original and sorted lists.
calories = {'Burger': 354, 'Fries': 365, 'Chicken': 149, 'Soda': 150}
sorted_calories = sorted(calories.items(), key=lambda x: x[1])
print("Sorted by calories:", sorted_calories)

Sorted by calories: [('Chicken', 149), ('Soda', 150), ('Burger', 354), ('Fries', 365)]


## TXT Files


### Write a TXT file

The code below creates a text file called *test.txt* and write a couple lines in it. 
Check and see where this file is located on your desk!

In [110]:
f = open('test.txt', 'w') # opened a file object *f* with the file name 'test.txt'; "w+" for the mode indicates write
for i in range(5):
    f.write(f"This is line {i+1}\n") #write 5 lines. Note the newline '\n' at the end of the string.
    
f.close() # It is good practice to close the file using f.close() in the end.

# Check your local folder and see whether the file 'test.txt' is created and contains the 5 lines.

# File gets sent to my downloads folder 

## Append to a TXT file
We can also append some string to the *test.txt* file. It is very similar to how we write the file, with only one difference - change the mode to 'a' instead. 

In [111]:
f = open('test.txt', 'a')
f.write(f"This is another line\n") #append a line
# Try to add more lines 
f.close()
# Check your local folder and see whether the file 'test.txt' is updated with the new line.
# Append more lines as needed.

#more lines appeared in the same test.txt file from the above code

## Reading a TXT File
Let's read in the *test.txt* file we created above and store all the contents in the file to a variable *content*.

In [112]:
# Add comments to explain the code.
f = open('./test.txt', 'r')
content = f.read()
f.close()
print(content)

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is another line



In [113]:
# Another way to read a file using 'with' statement
with open('test.txt', 'r') as f: 
    content = f.read()
f.close()
print(content)

This is line 1
This is line 2
This is line 3
This is line 4
This is line 5
This is another line



In [114]:
# Try to generate a new TXT file and write some data into it.
# Your code here
t = open('mycode.txt', 'w')
for p in range(8):
    t.write(f"Chicken and Fries are a great combination! {p+1}\n")



In [ ]:
# Try to read the TXT file you just created and print out the content.
# Your code here

In [115]:
t = open('./mycode.txt', 'r')
content = t.read()
t.close()
print(content)

Chicken and Fries are a great combination! 1
Chicken and Fries are a great combination! 2
Chicken and Fries are a great combination! 3
Chicken and Fries are a great combination! 4
Chicken and Fries are a great combination! 5
Chicken and Fries are a great combination! 6
Chicken and Fries are a great combination! 7
Chicken and Fries are a great combination! 8



## Dealing with numbers and arrays

Since we are working with numerical methods later, and many times, we work with the numbers or arrays. We could use the above methods to save the numbers or arrays to a file and read it back to the memory. But it is not so convenient this way. Instead, commonly we use the *numpy* package to directly save/read an array. For example, you can use np.savetxt & np.loadtxt as shown below. 


In [116]:
# Store an array to a file named *my_arr.txt* 
# and read it back to a variable called *my_arr*. 
import numpy as np
arr = np.array([[1.25, 2.21, 3.05], 
                [4.13, 5.75, 6.92]]) # Use np.array to create the array.
np.savetxt('my_arr.txt', arr, fmt='%.2f') #Save the array to a text file w/format and headers specified
my_arr = np.loadtxt('my_arr.txt')
print(my_arr)
# See whether the file 'my_arr.txt' is created in your local folder.

[[1.25 2.21 3.05]
 [4.13 5.75 6.92]]


In [117]:
# Try to make a 3x3 matrix using np.array and save it to a file named *my_matrix.txt*.
# Then read it back to a variable called *my_matrix* and print it out.
import numpy as np
matrix = np.array([[1, 3, 5],
                   [2, 4, 6],
                   [7, 9, 10]])
np.savetxt('my_matrix.txt', matrix, fmt='%.2f')
my_matrix = np.loadtxt('my_matrix.txt')
print(my_matrix)

[[ 1.  3.  5.]
 [ 2.  4.  6.]
 [ 7.  9. 10.]]


## Write and open a CSV file
CSV files store tabular data. Useful for lists, dictionaries, and arrays.
A simple example of using the random number generator to generate 100 rows and 5 columns of data 

In [ ]:
import numpy as np
data = np.random.random((100,3))
np.savetxt('test.csv', data, fmt = '%.2f', delimiter=',', header = 'c1, c2, c3')
# See whether the file 'test.csv' is created in your local folder.

# file saves as an excel sheet but can also be opened in python

## Read a CSV File
### Use *np.loadtxt* function
We could read in the csv file using the *np.loadtxt* function. Let's read in the csv file we just saved to the disk to a variable *my_csv*, and output the first 5 rows. Note here we use the *delimiter* again to specify that the data in the file is separated by commas. 

In [119]:
my_csv = np.loadtxt('./test.csv', delimiter=',')
my_csv[:10]

array([[0.26, 0.46, 0.55],
       [0.88, 0.87, 0.84],
       [0.22, 0.42, 0.57],
       [0.69, 0.55, 0.75],
       [0.26, 0.46, 0.99],
       [0.57, 0.25, 0.05],
       [0.88, 0.92, 0.48],
       [0.71, 0.63, 0.8 ],
       [0.35, 0.09, 0.64],
       [0.25, 0.68, 0.5 ]])

### Use *np.genfromtxt* to read the file and print out the data.

In [139]:
# Download the example.csv file from Canvas and put it in your local folder.
Data: Name (str), Age (int), City (str)
import numpy as np
data = np.genfromtxt('example.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
print(data) # Data contains names, ages and cities.
ages = data['Age']
print("Ages:", ages)
# Your code here to read the file and print out the data other than the "Age" column.

SyntaxError: invalid syntax (728966630.py, line 2)

In [ ]:
# got stuck with this code, unable to figure out how to fix the errors that would appear

### Sort data in CSV file and write the sorted data in a new CVS file

In [134]:
# Try to add more lines of data to example.csv by hand and sort the data based on age.

# Sort data based on ages (descending)
sorted_data = np.sort((data, order='Age')[::-1])
print(sorted_data)

# Header for the CSV file
header = 'Name, Age, City'

# Save the structured array to CSV.
# Use one format specifier per field in the structured array: Name (string), Age (int), City (string).
# Provide fmt as a list so the number of formats matches the number of columns.
np.savetxt('sorted_examples.csv', sorted_data, fmt=['%s','%d','%s'], delimiter=',', header=header, comments='')

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3381828005.py, line 4)

In [ ]:
# got stuck with this code, unable to figure out how to fix the errors that would appear

In [ ]:
# Use the random data generation code to create a CSV file of 100 data, between 0 to 1000. 
# Sort them and write them to a new "sorted" CSV file.
# You need to upload the original CSV file and the sorted CSV file. 